name: Automated Viral Twitter Bot

on:
  schedule:
    # Run at 5:00 AM IST (23:30 UTC previous day)
    - cron: '30 23 * * *'
    # Run at 5:00 PM IST (11:30 UTC same day)  
    - cron: '30 11 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  post-viral-tweet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Twitter Bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        TZ: Asia/Kolkata
      run: python twitter_bot.py
